spring:
  application:
    name: searchChampion-producer
  datasource:
    url: jdbc:mysql://cdb-ezjh4cma.bj.tencentcdb.com:10210/LolChampionInfo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abcd1234
    driverClassName: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 8003
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.eruka.searchChampionservice.model
  config-location: classpath:mybatis-config.xml
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
